[functions]
  directory = "src/netlify/functions"

[[headers]]
  for = "/.netlify/functions/stripe-webhook"
  [headers.values]
    Content-Type = "application/json"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/assets/images/*"
  to = "/.netlify/images?url=/assets/images/:splat"
  status = 200
